# Generated by Django 5.2.4 on 2025-08-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=4)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')])),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GradeReportModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('grade_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.gradereport')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.module')),
            ],
        ),
        migrations.AddField(
            model_name='gradereport',
            name='module',
            field=models.ManyToManyField(through='Core.GradeReportModule', to='Core.module'),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.student'),
        ),
    ]
